version: "3.3"

services:

  pg-db:
    image: postgres:12
    restart: always
    container_name: pg-db
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vsu
      POSTGRES_PASSWORD: pas
    networks:
      - vsu-net

networks:
  vsu-net: