version: "3.3"

services:

  postgres-database:
    image: postgres:12
    restart: always
    network_mode: host
    container_name: postgres-database
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vsu
      POSTGRES_PASSWORD: pas

  #-------------------------------------------

  vsu-service:
    image: elenbeilina/vsu-service:1
    container_name: vsu-service
    ports:
      - 8050:8050
    restart: always
    network_mode: host
    depends_on:
      - postgres-database