version: "3.3"

services:

  pg-db:
    image: postgres:12
    container_name: pg-db
    privileged: true
    ports:
      - 0.0.0.0:5432:5432
    labels:
      - works.weave.role=system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /data/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vsu
      POSTGRES_PASSWORD: pas
    command:
      - --probe.docker=true

  #-------------------------------------------

  vsu-service:
    image: elenbeilina/vsu-service:1
    container_name: vsu-service
    privileged: true
    ports:
      - 0.0.0.0:8050:8050
    labels:
      - works.weave.role=system
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command:
      - --probe.docker=true
    depends_on:
      - pg-db