version: "3.3"

services:
  pg-db:
    image: postgres:12
    restart: always
    container_name: pg-db
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vsu
      POSTGRES_PASSWORD: pas
    networks:
      - vsu-net

  vsu-service:
    image: elenbeilina/vsu-service:1
    container_name: vsu-service
    ports:
      - 8080:8080
    restart: always
    environment:
      - app_port=8080
      - server_postgres=pg-db
    depends_on:
      - pg-db
    networks:
      - vsu-net

networks:
  vsu-net: